name: vif
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        ocaml-version: [5.3.0, 5.4.0]
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          opam-local-packages: |
            *.opam
      - name: Install dependencies
        run: |
          opam install --deps-only -t vif
          opam install hurl
      - name: Build
        run: opam exec -- dune build -p vif
      - name: Test
        run: opam exec -- dune runtest -p vif
